In [1]:
import pandas as pd

df = pd.read_fwf("index.txt")
df.head()

State   Lat  Mort  Ocean   Long
0     Alabama  33.0   219      1   87.0
1     Arizona  34.5   160      0  112.0
2    Arkansas  35.0   170      0   92.5
3  California  37.5   182      1  119.5
4    Colorado  39.0   149      0  105.5

49

In [86]:
import numpy as np
nums = df.select_dtypes("number")
means = nums.agg("mean").values
matrix = nums.values.T

n = 4

cov = np.zeros((n,n))

for r in range(n):
    for c in range(n):
        cov[r][c] = (matrix[r]*matrix[c]).mean() - means[r]*means[c]

# remove bias
shap = nums.shape[0]
multi = shap/(shap-1)
cov_fin = cov*multi
print(cov_fin)

[[ 2.12601616e+01 -1.27085502e+02 -5.08715986e-01  6.78440051e+00]
 [-1.27085502e+02  1.11744303e+03  7.95195578e+00 -7.26495748e+01]
 [-5.08715986e-01  7.95195578e+00  2.52551020e-01 -2.85850340e+00]
 [ 6.78440051e+00 -7.26495748e+01 -2.85850340e+00  2.21012372e+02]]


In [91]:
stds = nums.std().values

corr = np.zeros((n,n))

for r in range(n):
    for c in range(n):
        corr[r][c] = cov_fin[r][c] / (stds[r]*stds[c])

print(corr)

[[ 1.         -0.82451779 -0.21954196  0.09897372]
 [-0.82451779  1.          0.4733547  -0.14618812]
 [-0.21954196  0.4733547   1.         -0.38260959]
 [ 0.09897372 -0.14618812 -0.38260959  1.        ]]


In [122]:
diagonal = np.sqrt(1/np.diag(cov))
digonal_in = np.zeros((n, n))
np.fill_diagonal(digonal_in, diagonal)
print(digonal_in@cov@digonal_in)

[[ 1.         -0.82451779 -0.21954196  0.09897372]
 [-0.82451779  1.          0.4733547  -0.14618812]
 [-0.21954196  0.4733547   1.         -0.38260959]
 [ 0.09897372 -0.14618812 -0.38260959  1.        ]]
